import { Product } from './types';
import imageP1 from './assets/images/regenerated_image_1779536893167.jpg';
import imageP3 from './assets/images/regenerated_image_1779514915498.webp';
import imageP5 from './assets/images/regenerated_image_1779536442324.webp';
import imageP6 from './assets/images/regenerated_image_1779536892248.avif';
import imageP7 from './assets/images/regenerated_image_1779536890593.jpg';
import imageP8 from './assets/images/regenerated_image_1779536888351.webp';
import imageP2 from './assets/images/regenerated_image_1779541037638.webp';
import imageP4 from './assets/images/regenerated_image_1779536293856.avif';
import imageP11 from './assets/images/regenerated_image_1779539523279.webp';
import imageP12 from './assets/images/regenerated_image_1779539524807.webp';
import imageP13 from './assets/images/regenerated_image_1779539520137.webp';
import imageP14 from './assets/images/regenerated_image_1779539526166.avif';
import imageP15 from './assets/images/regenerated_image_1779539527018.jpg';
import imageP16 from './assets/images/regenerated_image_1779539519194.jpg';
import imageP17 from './assets/images/regenerated_image_1779539515638.webp';
import imageP18 from './assets/images/regenerated_image_1779539528854.webp';
import imageP19 from './assets/images/regenerated_image_1779539530218.jpg';
import imageP20 from './assets/images/regenerated_image_1779539533039.avif';
import imageP21 from './assets/images/regenerated_image_1779539533786.webp';
import imageP22 from './assets/images/regenerated_image_1779539535443.webp';
import imageP23 from './assets/images/regenerated_image_1779539537050.webp';

export const mockProducts: Product[] = [
  {
    id: 'p1',
    name: 'Classic Denim Jacket',
    price: 45.0,
    category: 'Outerwear',
    ageGroup: '6-9',
    image: imageP1,
    rating: 4.8,
    reviews: 124,
    description: 'A rugged, classic denim jacket perfect for layering. Features soft cotton blend for active play and tag-free comfort.',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Blue Wash', 'Black'],
    badge: 'Bestseller'
  },
  {
    id: 'p2',
    name: 'Dino Graphic Tee',
    price: 18.0,
    category: 'Tops',
    ageGroup: '3-5',
    image: imageP2,
    rating: 4.9,
    reviews: 89,
    description: 'Write a playful 2-sentence description for a boy’s dinosaur t-shirt, highlighting comfort and fun design. 100% breathable organic cotton.',
    sizes: ['XS', 'S', 'M'],
    colors: ['Green', 'Navy', 'White'],
  },
  {
    id: 'p3',
    name: 'Streetwear Cargo Joggers',
    price: 32.0,
    category: 'Bottoms',
    ageGroup: '10-13',
    image: imageP3,
    rating: 4.6,
    reviews: 210,
    description: 'Trendy cargo joggers designed for both style and movement. Deep pockets and adjustable drawstring waist.',
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['Olive', 'Black', 'Khaki'],
    badge: 'New Arrival'
  },
  {
    id: 'p4',
    name: 'Colorblock Zip Hoodie',
    price: 38.0,
    category: 'Outerwear',
    ageGroup: '6-9',
    image: imageP4,
    rating: 4.7,
    reviews: 56,
    description: 'Warm fleece hoodie with a modern colorblock design. perfect for chilly school mornings.',
    sizes: ['S', 'M', 'L'],
    colors: ['Blue/Grey', 'Red/Navy'],
  },
  {
    id: 'p5',
    name: 'Performance Active Shorts',
    price: 22.0,
    category: 'Bottoms',
    ageGroup: '10-13',
    image: imageP5,
    rating: 4.5,
    reviews: 142,
    description: 'Lightweight performance shorts with moisture-wicking technology to keep them cool on the go.',
    sizes: ['M', 'L', 'XL'],
    colors: ['Black', 'Grey', 'Navy'],
    badge: 'Sale'
  },
  {
    id: 'p6',
    name: 'Everyday Stripe Polo',
    price: 24.0,
    category: 'Tops',
    ageGroup: '6-9',
    image: imageP6,
    rating: 4.4,
    reviews: 77,
    description: 'A preppy staple for family outings. Made from ultra-soft cotton pique.',
    sizes: ['S', 'M', 'L'],
    colors: ['Blue/White', 'Red/White'],
  },
  {
    id: 'p7',
    name: 'Oversized Checkered Flannel',
    price: 28.0,
    category: 'Tops',
    ageGroup: '10-13',
    image: imageP7,
    rating: 4.8,
    reviews: 95,
    description: 'Soft, brushed flannel shirt for a relaxed, layered look. Perfect for autumn weekends.',
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['Red/Black', 'Blue/Navy', 'Green/Black'],
  },
  {
    id: 'p8',
    name: 'Adventure Tech Vest',
    price: 34.0,
    category: 'Outerwear',
    ageGroup: '6-9',
    image: imageP8,
    rating: 4.5,
    reviews: 112,
    description: 'Lightweight insulated vest with zip pockets. Great extra layer for outdoor exploration.',
    sizes: ['S', 'M', 'L'],
    colors: ['Navy', 'Orange', 'Charcoal'],
    badge: 'Trending'
  },
  {
    id: 'p9',
    name: 'Classic Straight Denim',
    price: 35.0,
    category: 'Bottoms',
    ageGroup: '6-9',
    image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&auto=format&fit=crop&q=80',
    rating: 4.7,
    reviews: 320,
    description: 'Durable straight-leg jeans with an adjustable waistband for growing boys.',
    sizes: ['6Y', '8Y', '10Y', '12Y'],
    colors: ['Light Wash', 'Dark Wash', 'Black'],
  },
  {
    id: 'p10',
    name: 'Graphic Skater Hoodie',
    price: 42.0,
    category: 'Tops',
    ageGroup: '10-13',
    image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviews: 45,
    description: 'Heavyweight cotton hoodie featuring bold skate-inspired graphics. Ultra-cozy interior.',
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Grey Heather'],
    badge: 'Limited Edition'
  },
  {
    id: 'p11',
    name: 'Camo Print Windbreaker',
    price: 38.0,
    category: 'Outerwear',
    ageGroup: '6-12',
    image: imageP11,
    rating: 4.6,
    reviews: 58,
    description: 'Lightweight water-resistant windbreaker featuring a stylish camo print.',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Green Camo', 'Grey Camo'],
    badge: 'Water Resistant'
  },
  {
    id: 'p12',
    name: 'Everyday Chino Pants',
    price: 29.0,
    category: 'Bottoms',
    ageGroup: '6-12',
    image: imageP12,
    rating: 4.8,
    reviews: 142,
    description: 'Classic chino pants perfect for smart-casual wear. Includes adjustable waist.',
    sizes: ['6', '8', '10', '12'],
    colors: ['Khaki', 'Navy', 'Olive'],
  },
  {
    id: 'p13',
    name: 'Long Sleeve Raglan Tee',
    price: 22.0,
    category: 'Tops',
    ageGroup: '6-12',
    image: imageP13,
    rating: 4.5,
    reviews: 87,
    description: 'Sporty raglan tee with color-contrast sleeves. Soft and breathable cotton.',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['White/Navy', 'White/Red'],
  },
  {
    id: 'p14',
    name: 'Fleece Lined Puffer',
    price: 52.0,
    category: 'Outerwear',
    ageGroup: '6-12',
    image: imageP14,
    rating: 4.9,
    reviews: 205,
    description: 'Heavyweight puffer jacket with cozy fleece lining. Ultimate warmth for winter.',
    sizes: ['S', 'M', 'L'],
    colors: ['Black', 'Blue', 'Mustard'],
    badge: 'Winter Essential'
  },
  {
    id: 'p15',
    name: 'Casual Slip-on Sneakers',
    price: 36.0,
    category: 'Shoes',
    ageGroup: '6-12',
    image: imageP15,
    rating: 4.4,
    reviews: 334,
    description: 'Comfortable slip-on sneakers for active play. Durable rubber soles.',
    sizes: ['13', '1', '2', '3', '4'],
    colors: ['Black/White', 'Navy/White'],
  },
  {
    id: 'p16',
    name: 'Striped Crewneck Sweater',
    price: 31.0,
    category: 'Tops',
    ageGroup: '6-12',
    image: imageP16,
    rating: 4.7,
    reviews: 43,
    description: 'A warm knitted sweater featuring bold horizontal stripes. Great for layering.',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Navy/White', 'Red/Navy'],
  },
  {
    id: 'p17',
    name: 'Distressed Skinny Jeans',
    price: 34.0,
    category: 'Bottoms',
    ageGroup: '6-12',
    image: imageP17,
    rating: 4.8,
    reviews: 99,
    description: 'Modern skinny fit jeans with slight distressing details for a rugged look.',
    sizes: ['6', '8', '10', '12'],
    colors: ['Light Wash', 'Black'],
    badge: 'Trending'
  },
  {
    id: 'p18',
    name: 'Sporty Zip Track Jacket',
    price: 30.0,
    category: 'Outerwear',
    ageGroup: '6-12',
    image: imageP18,
    rating: 4.6,
    reviews: 120,
    description: 'Sleek track jacket with side pockets and a high collar. Perfect for PE and sports.',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black/Red', 'Navy/Blue'],
  },
  {
    id: 'p19',
    name: 'Graphic Print Logo Tee',
    price: 20.0,
    category: 'Tops',
    ageGroup: '6-12',
    image: imageP19,
    rating: 4.5,
    reviews: 211,
    description: 'Comfortable cotton tee featuring a cool abstract graphic logo print.',
    sizes: ['S', 'M', 'L'],
    colors: ['White', 'Heather Grey', 'Black'],
  },
  {
    id: 'p20',
    name: 'Woven Twill Cargo Shorts',
    price: 25.0,
    category: 'Bottoms',
    ageGroup: '6-12',
    image: imageP20,
    rating: 4.7,
    reviews: 65,
    description: 'Durable twill cargo shorts with plenty of pockets for daily adventures.',
    sizes: ['6', '8', '10', '12'],
    colors: ['Khaki', 'Navy'],
    badge: 'Restocked'
  },
  {
    id: 'p21',
    name: 'Premium Wool Blend Coat',
    price: 78.0,
    category: 'Outerwear',
    ageGroup: '13-18',
    image: imageP21,
    rating: 4.8,
    reviews: 44,
    description: 'A sophisticated wool-blend overcoat for older teens. Tailored fit for special occasions.',
    sizes: ['S', 'M', 'L'],
    colors: ['Camel', 'Charcoal', 'Navy'],
    badge: 'Premium Selection'
  },
  {
    id: 'p22',
    name: 'Vintage Wash Denim Jacket',
    price: 55.0,
    category: 'Outerwear',
    ageGroup: '13-18',
    image: imageP22,
    rating: 4.9,
    reviews: 130,
    description: 'Retro-inspired vintage wash denim jacket. A timeless streetwear essential.',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Light Vintage Wash', 'Acid Wash'],
  },
  {
    id: 'p23',
    name: 'Tapered Utility Trousers',
    price: 45.0,
    category: 'Bottoms',
    ageGroup: '13-18',
    image: imageP23,
    rating: 4.7,
    reviews: 82,
    description: 'Modern tapered fit utility trousers. Durable cotton blend with subtle side pockets.',
    sizes: ['28', '30', '32', '34'],
    colors: ['Olive', 'Black', 'Dark Grey'],
    badge: 'Editor’s Pick'
  },
  {
    id: 'p24',
    name: 'Heavyweight Graphic T-Shirt',
    price: 32.0,
    category: 'Tops',
    ageGroup: '13-18',
    image: 'https://images.unsplash.com/photo-1529374255404-311a2a4f1fd9?w=800&auto=format&fit=crop&q=80',
    rating: 4.6,
    reviews: 215,
    description: 'A boxy, heavyweight cotton t-shirt with a striking distressed back graphic.',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Off-White', 'Washed Black', 'Faded Green'],
  },
  {
    id: 'p25',
    name: 'Athletic Quarter-Zip Pullover',
    price: 48.0,
    category: 'Tops',
    ageGroup: '13-18',
    image: 'https://images.unsplash.com/photo-1622359265213-94c65529f796?w=800&auto=format&fit=crop&q=80',
    rating: 4.5,
    reviews: 110,
    description: 'Performance quarter-zip pullover in moisture-wicking fabric. Perfect for workouts.',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'Heather Grey', 'Navy'],
  },
  {
    id: 'p26',
    name: 'Slim Fit Chino Pants',
    price: 38.0,
    category: 'Bottoms',
    ageGroup: '13-18',
    image: 'https://images.unsplash.com/photo-1546419266-9ab867b14068?w=800&auto=format&fit=crop&q=80',
    rating: 4.7,
    reviews: 95,
    description: 'Sharply tailored slim-fit chinos for a smart-casual wardrobe. Features a slight stretch.',
    sizes: ['28', '30', '32', '34'],
    colors: ['Navy', 'Tan', 'Light Grey'],
  },
  {
    id: 'p27',
    name: 'Minimalist Windbreaker Anorak',
    price: 60.0,
    category: 'Outerwear',
    ageGroup: '13-18',
    image: 'https://images.unsplash.com/photo-1520975661595-6453be3f7070?w=800&auto=format&fit=crop&q=80',
    rating: 4.8,
    reviews: 67,
    description: 'Packs into its own pocket. This sleek anorak is water-repellent and completely windproof.',
    sizes: ['S', 'M', 'L'],
    colors: ['Black', 'Olive', 'Navy'],
    badge: 'Functional'
  },
  {
    id: 'p28',
    name: 'Textured Knit Polo',
    price: 35.0,
    category: 'Tops',
    ageGroup: '13-18',
    image: 'https://images.unsplash.com/photo-1520112690352-0cf79194e430?w=800&auto=format&fit=crop&q=80',
    rating: 4.6,
    reviews: 55,
    description: 'A refined knit polo shirt featuring a subtle ribbed texture and open collar design.',
    sizes: ['S', 'M', 'L'],
    colors: ['Cream', 'Navy', 'Brown'],
  },
  {
    id: 'p29',
    name: 'Relaxed Fit Carpenter Jeans',
    price: 49.0,
    category: 'Bottoms',
    ageGroup: '13-18',
    image: 'https://images.unsplash.com/photo-1627915579997-36e745f448c4?w=800&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviews: 140,
    description: 'On-trend relaxed fit jeans with carpenter pocket detailing and durable denim build.',
    sizes: ['28', '30', '32', '34'],
    colors: ['Washed Blue', 'Black'],
    badge: 'Bestseller'
  },
  {
    id: 'p30',
    name: 'Urban High-Top Sneakers',
    price: 85.0,
    category: 'Shoes',
    ageGroup: '13-18',
    image: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800&auto=format&fit=crop&q=80',
    rating: 4.7,
    reviews: 290,
    description: 'Premium faux-leather high tops built for everyday style. Cushioned insoles for all-day wear.',
    sizes: ['7', '8', '9', '10', '11'],
    colors: ['White/Black', 'All Black'],
  }
];
