import { Product } from './types';

export const mockProducts: Product[] = [
  {
    id: 'p1',
    name: 'Classic Denim Jacket',
    price: 45.0,
    category: 'Outerwear',
    ageGroup: '6-9',
    image: 'https://images.unsplash.com/photo-1519238263530-99bea0040286?w=800&auto=format&fit=crop&q=80',
    rating: 4.8,
    reviews: 124,
    description: 'A rugged, classic denim jacket perfect for layering. Features soft cotton blend for active play and tag-free comfort.',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Blue Wash', 'Black'],
    badge: 'Bestseller'
  },
  {
    id: 'p2',
    name: 'Dino Graphic Tee',
    price: 18.0,
    category: 'Tops',
    ageGroup: '3-5',
    image: 'https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?w=800&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviews: 89,
    description: 'Write a playful 2-sentence description for a boy’s dinosaur t-shirt, highlighting comfort and fun design. 100% breathable organic cotton.',
    sizes: ['XS', 'S', 'M'],
    colors: ['Green', 'Navy', 'White'],
  },
  {
    id: 'p3',
    name: 'Streetwear Cargo Joggers',
    price: 32.0,
    category: 'Bottoms',
    ageGroup: '10-13',
    image: 'https://images.unsplash.com/photo-1584448270104-583eb1ebde92?w=800&auto=format&fit=crop&q=80',
    rating: 4.6,
    reviews: 210,
    description: 'Trendy cargo joggers designed for both style and movement. Deep pockets and adjustable drawstring waist.',
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['Olive', 'Black', 'Khaki'],
    badge: 'New Arrival'
  },
  {
    id: 'p4',
    name: 'Colorblock Zip Hoodie',
    price: 38.0,
    category: 'Outerwear',
    ageGroup: '6-9',
    image: 'https://images.unsplash.com/photo-1503919005314-30d93d07d823?w=800&auto=format&fit=crop&q=80',
    rating: 4.7,
    reviews: 56,
    description: 'Warm fleece hoodie with a modern colorblock design. perfect for chilly school mornings.',
    sizes: ['S', 'M', 'L'],
    colors: ['Blue/Grey', 'Red/Navy'],
  },
  {
    id: 'p5',
    name: 'Performance Active Shorts',
    price: 22.0,
    category: 'Bottoms',
    ageGroup: '10-13',
    image: 'https://images.unsplash.com/photo-1606560938676-13d80327f2f1?w=800&auto=format&fit=crop&q=80',
    rating: 4.5,
    reviews: 142,
    description: 'Lightweight performance shorts with moisture-wicking technology to keep them cool on the go.',
    sizes: ['M', 'L', 'XL'],
    colors: ['Black', 'Grey', 'Navy'],
    badge: 'Sale'
  },
  {
    id: 'p6',
    name: 'Everyday Stripe Polo',
    price: 24.0,
    category: 'Tops',
    ageGroup: '6-9',
    image: 'https://images.unsplash.com/photo-1618331835717-801e976710b2?w=800&auto=format&fit=crop&q=80',
    rating: 4.4,
    reviews: 77,
    description: 'A preppy staple for family outings. Made from ultra-soft cotton pique.',
    sizes: ['S', 'M', 'L'],
    colors: ['Blue/White', 'Red/White'],
  }
];
